### ISSUE TITLE
[Addition] поиск

### ISSUE THREAD

**Issue by todeskin** [antonk9246/board#21]
полнотекстовый поиск объявлений по названию и описанию + возможность фильтровать объявления по категории (использовать встроенные механизмы PostgreSQL/sphinx/elasticsearch; при поиске название имеет больший вес), при подтверждении формы с поиском / фильтром обновления на странице делать с помощью AJAX. Сортировки тоже с помощью AJAX (http://guides.rubyonrails.org/working_with_javascript_in_rails.html). В фильтре показывать категории с количеством объявлений (в RoR есть counter_cache, всегда помнить про http://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations)

**Comment by antonk9246** [comment]
Показывать категории с количеством объявлений через  counter_cache не является целесообразным, т.к. он показывает объявления со всеми статусами, а нам нужны только со статусом approved
